Öppettider, ingen ändring i css
tuc-pixel-wizards/agilt-projektarbete-badhuset pull request #10
Opened 2023-10-20 11:46 UTC by SamuelHogberg

2023-10-20 12:29 UTC, karinEkenberg approved these changes
snyggt!

2023-10-20 14:38 UTC, diypa571 approved these changes

2023-10-21 04:10 UTC, rfhager requested changes
Tänkte bara att när inga ändringar är gjorda i CSS att det är onödigt att ladda upp en fil på nytt. Kan man ta bort CSS filen från denna commiten och uppdatera länken från HTML filen till den redan befintliga CSS filen som ligger i css/style.css?
I övrigt bra jobbat! 👍

2023-10-23 06:51 UTC, diypa571 approved these changes

2023-10-23 09:19 UTC, diypa571 approved these changes

2023-10-23 09:19 UTC, diypa571 approved these changes

2023-10-23 09:20 UTC, diypa571 approved these changes

2023-10-23 09:24 UTC, SamuelHogberg commented
> Tänkte bara att när inga ändringar är gjorda i CSS att det är onödigt att ladda upp en fil på nytt. Kan man ta bort CSS filen från denna commiten och uppdatera länken från HTML filen till den redan befintliga CSS filen som ligger i css/style.css? I övrigt bra jobbat! 👍

2023-10-23 09:24 UTC, closed without merging