Update index.html
tuc-pixel-wizards/agilt-projektarbete-badhuset pull request #14
Opened 2023-10-23 07:12 UTC by diypa571

Kommentärer

2023-10-23 07:46 UTC, rfhager requested changes
Varför har dessa ändringar gjorts, vilket Jira ID?

2023-10-23 10:05 UTC, IlhamAlf90 reviewed
skriv gärna kommentarer på engelska

2023-10-23 10:09 UTC, karinEkenberg approved these changes

2023-10-24 08:31 UTC, SamuelHogberg approved these changes

2023-10-25 07:34 UTC, IlhamAlf90 approved these changes

2023-10-25 07:34 UTC, IlhamAlf90 approved these changes

2023-10-25 07:35 UTC, SamuelHogberg approved these changes

2023-10-25 07:35 UTC, IlhamAlf90 approved these changes

2023-10-25 07:36 UTC, IlhamAlf90 approved these changes

2023-10-25 07:36 UTC, IlhamAlf90 approved these changes

2023-10-25 07:40 UTC, closed without merging