Update priser.html
tuc-pixel-wizards/agilt-projektarbete-badhuset pull request #15
Opened 2023-10-23 07:12 UTC by diypa571

Små ändringar

2023-10-23 07:47 UTC, rfhager requested changes
Varför har dessa ändringar gjorts, vilket Jira ID?

2023-10-23 09:37 UTC, rfhager approved these changes

2023-10-23 10:08 UTC, karinEkenberg approved these changes

2023-10-24 08:30 UTC, SamuelHogberg approved these changes

2023-10-24 09:11 UTC, merged