SCRUM-63
tuc-pixel-wizards/agilt-projektarbete-badhuset pull request #7
Opened 2023-10-19 14:33 UTC by SamuelHogberg

2023-10-19 14:35 UTC, rfhager approved these changes

2023-10-19 19:56 UTC, IlhamAlf90 approved these changes

2023-10-19 20:30 UTC, IlhamAlf90 approved these changes

2023-10-20 07:52 UTC, karinEkenberg requested changes
vi skulle inte använda js? och kommentarer på engelska? annars ser det snyggt ut! :)

2023-10-22 07:20 UTC, karinEkenberg approved these changes

2023-10-23 06:03 UTC, merged