Create index.html
tuc-pixel-wizards/agilt-projektarbete-badhuset pull request #8
Opened 2023-10-19 20:41 UTC by IlhamAlf90

index <Footer> till startsidan

2023-10-20 07:53 UTC, diypa571 approved these changes

2023-10-20 14:37 UTC, diypa571 approved these changes

2023-10-20 14:37 UTC, diypa571 approved these changes

2023-10-21 04:28 UTC, rfhager requested changes
Behöver uppdateras enligt de ändringar som diskuterades på reviewn.

- Ändring av plats på sociala medier samt adress
- Synka färgschema med headern

Utöver det så ser jag att det är satt en max-width på footern som gör att det ser lite tokigt ut, tanken var att den bara skulle gälla för allt innehåll på sidorna för att sakpa en enhetlighet för innehållet, förutom header och footer som bör löpa från sida till sida på skärmen.

Saknar png filerna för att få bilderna att fungera för ikonerna. Kan dessa kanske läggas till i en mapp som förslagsvis döps till img?

Ska denna CSS filen ligga rakt i repositoriet eller ska vi ha den i en mapp som heter CSS?

Ser att responsiviteten fungerar bra nu men att det blir ett stort tomrum längst ner i mobilvyn, kan man minska det?

2023-10-23 09:20 UTC, diypa571 approved these changes

2023-10-23 09:26 UTC, SamuelHogberg approved these changes

2023-10-24 08:35 UTC, karinEkenberg reviewed
Jag får inte fram bilderna i footern när jag tittar?

2023-10-24 08:41 UTC, IlhamAlf90 commented
jag ska försöka skicka de i en fil istället

2023-10-24 12:54 UTC, karinEkenberg approved these changes

2023-10-25 07:20 UTC, SamuelHogberg approved these changes

2023-10-25 07:20 UTC, rfhager approved these changes

2023-10-25 07:32 UTC, merged